language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t brktopcu/react-test -f Dockerfile.dev ./client

script:
  - docker run -e CI=true brktopcu/react-test npm run test

after_success:
  - docker build -t brktopcu/multi-client ./client
  - docker build -t brktopcu/multi-nginx ./nginx
  - docker build -t brktopcu/multi-server ./server
  - docker build -t brktopcu/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push brktopcu/multi-client
  - docker push brktopcu/multi-nginx
  - docker push brktopcu/multi-server
  - docker push brktopcu/multi-worker
